name: Build

on:
  schedule:
    # Every day at 9AM EST
    - cron:  '0 13 * * *'
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: sh prometheusDhMetricsStart.sh -d
      - name: Validate tables
        uses: deephaven/action-assert-dh-tables-present@v1
        with:
          table-names: result_dynamic,result_static,result_static_update,result_static_average,result_dynamic_update,result_dynamic_average,result_dynamic_downsampled_average,result_dynamic_downsampled_tail,result_dynamic_ema
          host: localhost
