name: Build

on:
  schedule:
    # Every day at 9AM EST
    - cron:  '0 13 * * *'
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: .github/scripts/build.sh

      - name: Test
        run: .github/scripts/test.sh
